// packages/home-page-react-mfe/src/bootstrapMfe.ts
import r2wc from '@r2wc/react-to-web-component';
import App from './app/app';

const mount = () => {
  if (customElements.get('home-page-react-mfe-wc-el')) {
    return;
  }

  const homePageReactMfe = r2wc(App);
  customElements.define('home-page-react-mfe-wc-el', homePageReactMfe);
};

export { mount };

// packages/home-page-react-mfe/src/bootstrapMfe.tsx
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';
import App from './app/app';

// home-page-react-mfe
const mount = (parentNode: HTMLElement) => {
  const root = ReactDOM.createRoot(parentNode);
  root.render(
    <StrictMode>
      <App />
    </StrictMode>
  );
};

export { mount };
