// packages/side-nav-bar-react-mfe/src/bootstrapMfe.tsx
import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';

import App from './app/app';

// side-nav-bar-react-mfe
const mount = (parentNode: HTMLElement) => {
  const root = ReactDOM.createRoot(parentNode);
  root.render(
    <StrictMode>
      <App />
    </StrictMode>
  );
};

export { mount };

// packages/side-nav-bar-react-mfe/src/bootstrapMfe.ts
import r2wc from '@r2wc/react-to-web-component';
import App from './app/app';

const mount = () => {
  if (customElements.get('side-nav-bar-react-mfe-wc-el')) {
    return;
  }

  const sideNavBarReactMfe = r2wc(App);
  customElements.define('side-nav-bar-react-mfe-wc-el', sideNavBarReactMfe);
};

export { mount };
